name: injection test (vulnerable)

on:
  issues:
    types: [opened]

jobs:
  issue-handler:
    runs-on: ubuntu-latest
    steps:
      - name: vulnerable issue title usage
        shell: bash
        run: |
          echo "new issue title is: ${{ github.event.issue.title }}"
