name: secret test

on:
  workflow_dispatch:

jobs:
  secret-check:
    runs-on: ubuntu-latest

    steps:
      - name: attempt to print secret
        run: echo "deployment token is ${{ secrets.MY_SENSITIVE_TOKEN }}"
